version: '3'

services:
  broker-service:
    build:
      context: ./broker-service
      dockerfile: ./broker-service.dockerfile
    ports:
      - "8080:5000"
    deploy:
      mode: replicated
      replicas: 1