// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"time"
)

type Log struct {
	ID        int64
	Email     string
	Data      string
	UserIp    string
	UserAgent string
	LoggedAt  time.Time
}
